name: build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: sbt

    - uses: sbt/setup-sbt@v1

    - run: sbt test
